version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: mongo_festivos
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - red_festivos

  api:
    build: .
    container_name: api_festivos
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/festivos
    networks:
      - red_festivos

volumes:
  mongo_data:

networks:
  red_festivos:
